spec:
  inputs:
    docker_image:
      description: 'Docker image to use for build'
      type: string
    flavor:
      description: 'Flavor to build for'
      options: [development, staging, production]

---
build_ios_$[[ inputs.flavor ]]:
  stage: build
  needs: []
  tags:
    - {{ gitlab_ios_runner_tag }}
  image: $[[ inputs.docker_image ]]
  script:
    - flutter clean
    - flutter pub run build_runner build --delete-conflicting-outputs
    - flutter build ios --no-codesign --release --flavor $[[ inputs.flavor ]] -t lib/main_$[[ inputs.flavor ]].dart

build_android_$[[ inputs.flavor ]]:
  stage: build
  needs: []
  tags:
    - saas-linux-small-amd64
  image: $[[ inputs.docker_image ]]
  variables:
    SECURE_FILES_DOWNLOAD_PATH: ./android/app
    ANDROID_KEYSTORE_PATH: upload-keystore.jks
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - flutter clean
    - dart run build_runner build --delete-conflicting-outputs
    - flutter build appbundle --release --flavor $[[ inputs.flavor ]] -t lib/main_$[[ inputs.flavor ]].dart
