name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  formigas_mvc:
    git:
      url: git@git.dev.formigas.de:framework/flutter-mvc.git
      ref: main
  freezed_annotation: ^2.4.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.0


dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
