name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=3.22.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  {{#use_svg}}flutter_svg: ^2.0.9{{/use_svg}}
  {{#use_freezed}}freezed_annotation: ^2.4.1{{/use_freezed}}
  go_router: ^14.2.0
  intl: ^0.19.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  {{#use_freezed}}freezed: ^2.4.7{{/use_freezed}}
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/common/assets/
  {{#use_svg}}integrations:{{/use_svg}}
    {{#use_svg}}flutter_svg: true{{/use_svg}}

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/