name: Continuous Integration

permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches: [develop, staging, master, main]
  pull_request:

env:
  FLUTTER_VERSION: "3.13.9"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{#mustacheCase}}env.FLUTTER_VERSION{{/mustacheCase}}
          cache: true
      - name: Format
        run: dart format -o none --set-exit-if-changed lib/ test/
      - name: Build runner
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze --fatal-infos --fatal-warnings

  determine-flavor:
    name: Determine Flavor
    runs-on: ubuntu-latest
    outputs:
      flavor: ${{#mustacheCase}}steps.set-flavor.outputs.flavor{{/mustacheCase}}
    steps:
      - name: Determine Flavor
        id: set-flavor
        run: |
          if [[ "${{#mustacheCase}}github.ref{{/mustacheCase}}" == "refs/heads/master" || "${{#mustacheCase}}github.ref{{/mustacheCase}}" == "refs/heads/main" ]]; then
            echo "flavor=production" >> $GITHUB_OUTPUT
          elif [[ "${{#mustacheCase}}github.ref{{/mustacheCase}}" == "refs/heads/staging" ]]; then
            echo "flavor=staging" >> $GITHUB_OUTPUT
          else
            echo "flavor=development" >> $GITHUB_OUTPUT
          fi

  build_ios:
    name: Build iOS ${{#mustacheCase}}needs.determine-flavor.outputs.flavor{{/mustacheCase}}
    needs: determine-flavor
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{#mustacheCase}}env.FLUTTER_VERSION{{/mustacheCase}}
          cache: true
      - name: Clean
        run: flutter clean
      - name: Build runner
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Build
        run: flutter build ios --no-codesign --release --flavor ${{#mustacheCase}}needs.determine-flavor.outputs.flavor{{/mustacheCase}} -t lib/main_${{#mustacheCase}}needs.determine-flavor.outputs.flavor{{/mustacheCase}}.dart

  build_android:
    name: Build Android ${{#mustacheCase}}needs.determine-flavor.outputs.flavor{{/mustacheCase}}
    needs: determine-flavor
    runs-on: ubuntu-latest
    env:
      KEYSTORE_FILENAME: upload-keystore.jks
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{#mustacheCase}}env.FLUTTER_VERSION{{/mustacheCase}}
          cache: true
      - name: Setup Keystore
        run: echo "${{#mustacheCase}}secrets.ANDROID_KEYSTORE_BASE64{{/mustacheCase}}" | base64 --decode > ./android/app/${{#mustacheCase}}env.KEYSTORE_FILENAME{{/mustacheCase}}
      - name: Clean
        run: flutter clean
      - name: Build runner
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Build
        run: flutter build appbundle --release --flavor ${{#mustacheCase}}needs.determine-flavor.outputs.flavor{{/mustacheCase}} -t lib/main_${{#mustacheCase}}needs.determine-flavor.outputs.flavor{{/mustacheCase}}.dart
        env:
          ANDROID_KEYSTORE_PATH: ${{#mustacheCase}}env.KEYSTORE_FILENAME{{/mustacheCase}}
          ANDROID_KEYSTORE_PASSWORD: ${{#mustacheCase}}secrets.ANDROID_KEYSTORE_PASSWORD{{/mustacheCase}}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{#mustacheCase}}secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD{{/mustacheCase}}
          ANDROID_KEYSTORE_ALIAS: ${{#mustacheCase}}vars.ANDROID_KEYSTORE_ALIAS{{/mustacheCase}}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{#mustacheCase}}env.FLUTTER_VERSION{{/mustacheCase}}
          cache: true
      - name: Install lcov
        run: |
          sudo apt-get update
          sudo apt-get -y install lcov
      - name: Clean
        run: flutter clean
      - name: Build runner
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Run tests
        run: flutter test --coverage --file-reporter json:test_results.json
      - name: Remove generated files from coverage
        run: lcov --remove coverage/lcov.info '**.g.dart'  -o coverage/clean_lcov.info
      - name: Publish test results
        uses: dorny/test-reporter@v1.8.0
        if: success() || failure()
        with:
          name: Unit tests report
          path: test_results.json
          reporter: flutter-json
          max-annotations: 50
          token: ${{#mustacheCase}}secrets.GITHUB_TOKEN{{/mustacheCase}}
      - name: Publish coverage report
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage/clean_lcov.info
          minimum-coverage: 50
          artifact-name: code-coverage-report
          github-token: ${{#mustacheCase}}secrets.GITHUB_TOKEN{{/mustacheCase}}
          update-comment: true
          additional-message: Remember that you want to write high quality tests, so you can sleep well at night!
