name: formigas_codemagic
description: A brick that provides a Codemagic CI pipeline for Flutter projects.
repository: https://github.com/formigas/formigas-flutter-bricks.git
version: 0.1.0

environment:
  mason: ">=0.1.0-dev.60 <0.1.0"
