variables:
  FLUTTER_VERSION: "3.24.3"
  FLUTTER_DOCKER_IMAGE: "ghcr.io/cirruslabs/flutter:${FLUTTER_VERSION}"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

include:
  - local: "templates/build.yml"
    inputs:
      docker_image: $FLUTTER_DOCKER_IMAGE

stages:
  - validate
  - build
  - test

validate:
  stage: validate
  image: $FLUTTER_DOCKER_IMAGE
  script:
    - dart format -o none --set-exit-if-changed lib/ test/
    - dart run build_runner build --delete-conflicting-outputs
    - flutter analyze --fatal-infos --fatal-warnings

test:
  stage: test
  needs: []
  image: $FLUTTER_DOCKER_IMAGE
  script:
    - flutter pub global activate junitreport
    - set -o pipefail
    - flutter clean
    - dart run build_runner build --delete-conflicting-outputs
    - flutter test --machine --coverage | $HOME/.pub-cache/bin/tojunit > test-report-app.xml
    - flutter pub global activate cobertura
    - $HOME/.pub-cache/bin/cobertura convert -i coverage/lcov.info -o coverage/cobertura.xml -p pubspec.yaml
    - apt update && apt install -y lcov
    - genhtml -o docs/coverage/ --no-function-coverage --no-branch-coverage coverage/lcov.info
    - lcov --list coverage/lcov.info
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    when: always
    reports:
      junit: test-report-app.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura.xml
    paths:
      - coverage/lcov.info
      - coverage/cobertura.xml
      - docs/coverage/
      - test-report-app.xml
    expire_in: 1 week
  rules:
