name: formigas_codemagic brick CI

on:
  pull_request:
    paths:
      - formigas_codemagic/**
      - .github/workflows/continuous-integration-formigas_codemagic.yaml
      - .github/workflows/check-codemagic-ci-label.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  create-pr-with-changes:
    name: Create PR with changes in test repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout brick repository
        uses: actions/checkout@v4
        with:
          path: formigas-flutter-bricks

      - name: Create GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.FORMIGAS_VERSION_BUMPER_APP_ID }}
          private-key: ${{ secrets.FORMIGAS_VERSION_BUMPER_PRIVATE_KEY }}

      - name: Checkout codemagic test repository
        uses: actions/checkout@v4
        with:
          repository: formigas/codemagic-ci-brick-ci
          token: ${{ steps.app-token.outputs.token }}
          path: codemagic-ci-brick-ci

      - name: Install Flutter
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Mason CLI
        run: dart pub global activate mason_cli

      - name: Initialize Mason
        run: mason init

      - name: Add formigas_codemagic with Mason
        run: mason add formigas_codemagic --path ./formigas-flutter-bricks/formigas_codemagic

      - name: Make formigas_codemagic
        run: mason make formigas_codemagic
        working-directory: codemagic-ci-brick-ci

      - name: Commit changes to test repository
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          BRANCH_NAME="codemagic-ci-changes-$PR_NUMBER"
          git config --global user.name "formigas-flik[bot]"
          git config --global user.email "173810882+formigas-flik[bot]@users.noreply.github.com"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Update codemagic CI workflow for PR $PR_NUMBER"
          git push origin $BRANCH_NAME
        working-directory: codemagic-ci-brick-ci

      - name: Create PR
        run: |
          gh auth login --with-token < ${{ steps.app-token.outputs.token }}
          if ! gh pr list --head $BRANCH_NAME --json number | grep -q '"number":'; then
            gh pr create --base main --head $BRANCH_NAME --title "Automated PR for Codemagic CI changes" --body "This PR is automatically generated by the CI workflow. It will merge the changes made in the CI workflow into the main branch. Once the pipelines succeed, this PR will be automatically merged."
          else
            echo "PR already exists. Skipping creation."
          fi
          gh pr merge $BRANCH_NAME --auto
        working-directory: codemagic-ci-brick-ci
