name: Publish formigas_bitbucket_pipelines on BrickHub

on:
  push:
    tags:
      - "formigas_bitbucket_pipelines-*.*.*"

jobs:
  publish:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/mason_publish.yml@v1
    with:
      working_directory: ./formigas_bitbucket_pipelines
    secrets:
      mason_credentials: ${{ secrets.MASON_CREDENTIALS }}
