name: Publish formigas_gitlab_ci on BrickHub

on:
  push:
    tags:
      - "formigas_gitlab_ci-*.*.*"

jobs:
  publish:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/mason_publish.yml@v1
    with:
      working_directory: ./formigas_gitlab_ci
    secrets:
      mason_credentials: ${{ secrets.MASON_CREDENTIALS }}
