name: Publish formigas_feature on BrickHub

on:
  push:
    branches:
      - main
    tags:
      - "formigas_feature-*.*.*"

jobs:
  publish:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/mason_publish.yml@v1
    with:
      working_directory: ./formigas_feature
    secrets:
      mason_credentials: ${{ secrets.MASON_CREDENTIALS }}
