name: Release formigas_fastlane_cd brick

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 1.0.0)"
        required: true

jobs:
  release-brick:
    uses: ./.github/workflows/release-brick.yaml
    with:
      version: ${{ github.event.inputs.version }}
      brick_name: formigas_fastlane_cd
    secrets:
      FORMIGAS_VERSION_BUMPER_APP_ID: ${{ vars.FORMIGAS_VERSION_BUMPER_APP_ID }}
      FORMIGAS_VERSION_BUMPER_PRIVATE_KEY: ${{ secrets.FORMIGAS_VERSION_BUMPER_PRIVATE_KEY }}
